In [2]:
# Import libraries
import pandas as pd
import numpy as np
import plotly.express as px

# Data Loading

In [3]:
from dotenv import load_dotenv

load_dotenv() # Load environment variables from .env dile

True

In [4]:
import mysql.connector
import os

os.getenv('MYSQL_USER')

'root'

In [5]:
conn = mysql.connector.connect(
    host = os.getenv('MYSQL_HOST'),
    user = os.getenv('MYSQL_USER'),
    password = os.getenv('MYSQL_PASSWORD'),
    database = os.getenv('MYSQL_DATABASE')
)

- Load customers

In [6]:
query = '''
SELECT * FROM customers;
'''
customers = pd.read_sql(sql = query, con = conn)
customers.head(2)

C:\Users\hp\AppData\Local\Temp\ipykernel_31408\1821516742.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql(sql = query, con = conn)

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,Zabrina Harrowsmith,Genderfluid,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia

- Load orders

In [7]:
query = '''
SELECT * FROM orders;
'''
orders = pd.read_sql(sql = query, con = conn)
orders.head(2)

C:\Users\hp\AppData\Local\Temp\ipykernel_31408\933796974.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql(sql = query, con = conn)

   order_id  customer_id  order_date delivery_date
0         1           64  2021-08-30    2021-09-24
1         2          473  2021-02-03    2021-02-13

- Load products

In [8]:
query = '''
SELECT * FROM products;
'''
products = pd.read_sql(sql = query, con = conn)
products.head(2)

C:\Users\hp\AppData\Local\Temp\ipykernel_31408\2372767046.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql(sql = query, con = conn)

,product_id,product_type,product_name,size,colour,quantity,description
0,0,Shirt,Oxford Cloth,XS,red,66,"A red coloured, XS sized, Oxford Cloth Shirt"
1,1,Shirt,Oxford Cloth,S,red,53,"A red coloured, S sized, Oxford Cloth Shirt"

- Load sales

In [9]:
query = '''
SELECT * FROM sales;
'''
sales = pd.read_sql(sql = query, con = conn)
sales.head(2)

C:\Users\hp\AppData\Local\Temp\ipykernel_31408\2260084056.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales = pd.read_sql(sql = query, con = conn)

   sales_id  order_id  product_id  price_per_unit  quantity  total_price
0         0         1         218           106.0         2        212.0
1         1         1         481           118.0         1        118.0

- Merge 'customers' with 'orders'

In [10]:
df = pd.merge(left = customers, right = orders, how = 'inner', on = 'customer_id')
df.head(2)

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,2021-05-08,2021-05-20
1,20,Gigi Kalaher,Genderqueer,55,2069 Phoebe MallApt. 543,6318,East Audrey,South Australia,Australia,432,2021-10-20,2021-11-03

- Merge with 'sales'

In [11]:
df = pd.merge(left = df, right = sales, how = 'inner', on = 'order_id')
df.head(2)

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,2021-05-08,2021-05-20,1018,837,117.0,1,117.0
1,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,2021-05-08,2021-05-20,1019,428,107.0,2,214.0

- Merge with 'products'

In [12]:
df = pd.merge(left = df, right = products, how = 'inner', on = 'product_id')
df.head(2)

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,...,product_id,price_per_unit,quantity_x,total_price,product_type,product_name,size,colour,quantity_y,description
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,...,837,117.0,1,117.0,Jacket,Shearling,M,violet,74,"A violet coloured, M sized, Shearling Jacket"
1,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,...,428,107.0,2,214.0,Jacket,Denim,L,orange,73,"A orange coloured, L sized, Denim Jacket"

# To show all columns in the dataframe

In [13]:
pd.set_option('display.max_columns', None)

In [14]:
df.head(2)

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity_x,total_price,product_type,product_name,size,colour,quantity_y,description
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,2021-05-08,2021-05-20,1018,837,117.0,1,117.0,Jacket,Shearling,M,violet,74,"A violet coloured, M sized, Shearling Jacket"
1,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,2021-05-08,2021-05-20,1019,428,107.0,2,214.0,Jacket,Denim,L,orange,73,"A orange coloured, L sized, Denim Jacket"

In [15]:
df.rename(columns = {'quantity_x': 'quantity', 'quantity_y': 'stock'}, inplace = True)
df = df.sort_values(by = 'customer_id', ascending = True).reset_index(drop = True)
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,stock,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,2021-03-06,2021-04-01,3326,179,98.0,1,98.0,Shirt,Camp Collared,XL,red,79,"A red coloured, XL sized, Camp Collared Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,729,2021-02-18,2021-03-01,3640,558,98.0,1,98.0,Jacket,Leather,L,violet,78,"A violet coloured, L sized, Leather Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,729,2021-02-18,2021-03-01,3639,197,98.0,3,294.0,Shirt,Camp Collared,M,blue,65,"A blue coloured, M sized, Camp Collared Shirt"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,2021-03-06,2021-04-01,3327,789,91.0,3,273.0,Jacket,Pullover,XL,green,65,"A green coloured, XL sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,2021-04-04,2021-04-06,2246,783,91.0,2,182.0,Jacket,Pullover,L,yellow,43,"A yellow coloured, L sized, Pullover Jacket"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,2021-10-11,2021-10-13,4479,1070,93.0,3,279.0,Trousers,Joggers,XS,blue,67,"A blue coloured, XS sized, Joggers Trousers"
4996,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,2021-10-11,2021-10-13,4480,1177,99.0,2,198.0,Trousers,High-Waisted,M,blue,52,"A blue coloured, M sized, High-Waisted Trousers"
4997,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,2021-10-11,2021-10-13,4482,109,92.0,3,276.0,Shirt,Denim,XL,red,63,"A red coloured, XL sized, Denim Shirt"
4998,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,2021-10-11,2021-10-13,4481,1239,112.0,1,112.0,Trousers,Tracksuit Bottoms,XL,yellow,59,"A yellow coloured, XL sized, Tracksuit Bottoms..."
4999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,2021-10-11,2021-10-13,4477,160,91.0,3,273.0,Shirt,Linen,XS,blue,53,"A blue coloured, XS sized, Linen Shirt"

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     5000 non-null   int64
 1   customer_name   5000 non-null   str
 2   gender          5000 non-null   str
 3   age             5000 non-null   int64
 4   home_address    5000 non-null   str
 5   zip_code        5000 non-null   str
 6   city            5000 non-null   str
 7   state           5000 non-null   str
 8   country         5000 non-null   str
 9   order_id        5000 non-null   int64
 10  order_date      5000 non-null   object
 11  delivery_date   5000 non-null   object
 12  sales_id        5000 non-null   int64
 13  product_id      5000 non-null   int64
 14  price_per_unit  5000 non-null   float64
 15  quantity        5000 non-null   int64
 16  total_price     5000 non-null   float64
 17  product_type    5000 non-null   str
 18  product_name    5000 non-null   str
 19  size            5000 non-null   str
 20  colour          5000 non-null   str
 21  stock           5000 non-null   int64
 22  description     5000 non-null   str
dtypes: float64(2), int64(7), object(2), str(12)
memory usage: 1.6+ MB

In [17]:
# df duplicates
df.duplicated().sum()

np.int64(0)

# 3.1 Check Summary for numerical columns

In [18]:
df.describe().round(2)

,customer_id,age,order_id,sales_id,product_id,price_per_unit,quantity,total_price,stock
count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.0,5000.00,5000.00,5000.00
mean,504.56,48.76,503.04,2499.50,634.05,103.5,1.99,206.36,60.08
std,276.50,17.58,285.96,1443.52,363.26,9.2,0.81,86.36,11.68
min,1.00,20.00,1.00,0.00,1.00,90.0,1.00,90.00,40.00
25%,276.00,34.00,258.00,1249.75,323.00,95.0,1.00,112.00,50.00
50%,509.00,48.00,504.50,2499.50,635.00,102.0,2.00,204.00,60.00
75%,733.00,63.00,749.00,3749.25,951.00,112.0,3.00,285.00,70.00
max,1000.00,80.00,999.00,4999.00,1259.00,119.0,3.00,357.00,80.00

# 3.2 Check Summary for Categorical columns

In [19]:
df.describe(include= [str]).round(2)

,customer_name,gender,home_address,zip_code,city,state,country,product_type,product_name,size,colour,description
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,616,8,616,603,604,8,1,3,35,5,7,1233
top,Kristofor Roos,Female,5567 Clarke MallApt. 756,4043,Jordanside,South Australia,Australia,Trousers,Denim,M,blue,"A orange coloured, L sized, Flannel Shirt"
freq,37,712,37,37,37,718,5000,1683,273,1022,762,13

# 4. Check missing values

In [20]:
# check missing values by count
df.isna().sum()

customer_id       0
customer_name     0
gender            0
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
order_id          0
order_date        0
delivery_date     0
sales_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
product_type      0
product_name      0
size              0
colour            0
stock             0
description       0
dtype: int64

# Data Cleaning

In [21]:
# Drop unnecessary columns
df.drop(['country', 'home_address', 'zip_code', 'description'], axis = 1, inplace = True)
df.duplicated().sum()

np.int64(0)

In [22]:
df.head()

,customer_id,customer_name,gender,age,city,state,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,stock
0,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,670,2021-03-06,2021-04-01,3326,179,98.0,1,98.0,Shirt,Camp Collared,XL,red,79
1,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,729,2021-02-18,2021-03-01,3640,558,98.0,1,98.0,Jacket,Leather,L,violet,78
2,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,729,2021-02-18,2021-03-01,3639,197,98.0,3,294.0,Shirt,Camp Collared,M,blue,65
3,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,670,2021-03-06,2021-04-01,3327,789,91.0,3,273.0,Jacket,Pullover,XL,green,65
4,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,455,2021-04-04,2021-04-06,2246,783,91.0,2,182.0,Jacket,Pullover,L,yellow,43

In [23]:
# Convert order_date and delivery_date to datetime
df['order_date'] = pd.to_datetime(df['order_date'])
df['delivery_date'] = pd.to_datetime(df['delivery_date'])

- In depth check for numerical columns

In [24]:
num_cols = df.select_dtypes(include = 'number').columns.drop(['customer_id', 'order_id', 'product_id', 'sales_id'])
num_cols

Index(['age', 'price_per_unit', 'quantity', 'total_price', 'stock'], dtype='str')

In [25]:
for col in num_cols:
    px.histogram(df, x = col, title = f'Histogram of {col}').show()

# In depth check for categorical columns

In [26]:
cat_cols = df.select_dtypes(include = 'object').columns
cat_cols

C:\Users\hp\AppData\Local\Temp\ipykernel_31408\427634010.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include = 'object').columns

Index(['customer_name', 'gender', 'city', 'state', 'product_type',
       'product_name', 'size', 'colour'],
      dtype='str')

In [27]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 50)

customer_name
616
<ArrowStringArray>
[      'Leanna Busson',     'Winslow Ewbanck',   'Susanetta Wilshin',
 'Michaeline McIndrew',        'Fedora Dmych',     'Marabel Swinfon',
      'Avril Rossiter',   'Gabbie Aldwinckle',       'Chan Duchesne',
    'Chadwick Cruddas',
 ...
        'Grady Wipper',        'Tommie Benoy',      'Sauncho Boosey',
    'Cristina Jowling',     'Orella Singyard',       'Vanna Densham',
       'Leandra Derks',      'Elvira Sarfati',      'Rebecka Fabler',
    'Mandel Fairbanks']
Length: 616, dtype: str
--------------------------------------------------
gender
8
<ArrowStringArray>
[     'Female',    'Bigender',     'Agender',        'Male', 'Genderfluid',
 'Genderqueer',  'Non-binary',  'Polygender']
Length: 8, dtype: str
--------------------------------------------------
city
604
<ArrowStringArray>
[     'Johnstonhaven',          'Masonfurt',          'Joelburgh',
         'Georgeland',        'Taylorburgh',      'Maddisonmouth',
         'Kiehnburgh',            'New Kai',         'Walterland',
        'West Bailey',
 ...
       'Thompsonbury',          'New Harry',        'Stewartland',
       'North Andrew',        'Michaelberg',          'Hallshire',
      'Hermistonberg',    'Lake Danielland',         'Kohlerberg',
 'Lake Audreyborough']
Length: 604, dtype: str
--------------------------------------------------
state
8
<ArrowStringArray>
[          'Northern Territory',                   'Queensland',
            'Western Australia',              'South Australia',
                     'Victoria',              'New South Wales',
                     'Tasmania', 'Australian Capital Territory']
Length: 8, dtype: str
--------------------------------------------------
product_type
3
<ArrowStringArray>
['Shirt', 'Jacket', 'Trousers']
Length: 3, dtype: str
--------------------------------------------------
product_name
35
<ArrowStringArray>
[    'Camp Collared',           'Leather',          'Pullover',
          'Chambray',           'Cropped', 'Tracksuit Bottoms',
         'Shearling',              'Wool',   'Casual Slim Fit',
       'Relaxed Leg',             'Linen',            'Bomber',
       'Windbreaker',           'Pleated',             'Coach',
            'Chinos',            'Puffer',          'Cardigan',
      'Oxford Cloth',             'Denim',           'Peacoat',
      'High-Waisted',          'Slim-Fit',           'Flannel',
        'Drawstring',       'Trench Coat',           'Joggers',
      'Cuban Collar',   'Mandarin Collar',       'Cargo Pants',
             'Cords',             'Dress',             'Parka',
            'Henley',              'Polo']
Length: 35, dtype: str
--------------------------------------------------
size
5
<ArrowStringArray>
['XL', 'L', 'M', 'S', 'XS']
Length: 5, dtype: str
--------------------------------------------------
colour
7
<ArrowStringArray>
['red', 'violet', 'blue', 'green', 'yellow', 'orange', 'indigo']
Length: 7, dtype: str
--------------------------------------------------

# Feature Engineering

In [28]:
df['order_date'].describe()

count                   5000
mean     2021-05-25 15:10:39
min      2021-01-01 00:00:00
25%      2021-03-13 00:00:00
50%      2021-05-24 00:00:00
75%      2021-08-08 00:00:00
max      2021-10-24 00:00:00
Name: order_date, dtype: object

In [29]:
# Create month, day and weekday columns from order_date
# df['order_year'] = df['order_date'].dt.year won't do it because all the orders are in the same year (2023), so we will only create month and day columns
df['order_month_name'] = df['order_date'].dt.month_name()
df['order_day'] = df['order_date'].dt.day
df['order_weekday_name'] = df['order_date'].dt.day_name()

In [30]:
df['delivery_days'] = (df['delivery_date'] - df['order_date']).dt.days

# Data Analysis

In [31]:
# How many customers per state?
df.groupby('state')['customer_id'].nunique()

state
Australian Capital Territory    73
New South Wales                 77
Northern Territory              75
Queensland                      79
South Australia                 90
Tasmania                        67
Victoria                        75
Western Australia               80
Name: customer_id, dtype: int64

In [32]:
from cProfile import label


px.bar(df.groupby('state')['customer_id'].nunique().sort_values(ascending=True).reset_index(), y = 'state', x = 'customer_id', title = 'Number of Customers per State', text_auto=True,
       labels={'customer_id': 'Number of Customers'}
       ).show()

In [33]:
# Sales trend over time
sorted_df = df.sort_values(by = 'order_date')
plot_df = sorted_df.groupby('order_date')['total_price'].sum().reset_index()
plot_df

    order_date  total_price
0   2021-01-01       3196.0
1   2021-01-02       5374.0
2   2021-01-03       2631.0
3   2021-01-04       4223.0
4   2021-01-05       5906.0
..         ...          ...
286 2021-10-20       2570.0
287 2021-10-21       6423.0
288 2021-10-22       4788.0
289 2021-10-23       2068.0
290 2021-10-24       4015.0

[291 rows x 2 columns]

In [34]:
px.line(plot_df, x = 'order_date', y = 'total_price', title = 'Sales Trend Over Time', labels={'total_price': 'Total Sales ($)', 'order_date': 'Order Date'}).show()

In [35]:
df['month'] = df['order_date'].dt.month
df

,customer_id,customer_name,gender,age,city,state,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,stock,order_month_name,order_day,order_weekday_name,delivery_days,month
0,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,670,2021-03-06,2021-04-01,3326,179,98.0,1,98.0,Shirt,Camp Collared,XL,red,79,March,6,Saturday,26,3
1,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,729,2021-02-18,2021-03-01,3640,558,98.0,1,98.0,Jacket,Leather,L,violet,78,February,18,Thursday,11,2
2,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,729,2021-02-18,2021-03-01,3639,197,98.0,3,294.0,Shirt,Camp Collared,M,blue,65,February,18,Thursday,11,2
3,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,670,2021-03-06,2021-04-01,3327,789,91.0,3,273.0,Jacket,Pullover,XL,green,65,March,6,Saturday,26,3
4,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,455,2021-04-04,2021-04-06,2246,783,91.0,2,182.0,Jacket,Pullover,L,yellow,43,April,4,Sunday,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Mandel Fairbanks,Male,71,Lake Audreyborough,Tasmania,894,2021-10-11,2021-10-13,4479,1070,93.0,3,279.0,Trousers,Joggers,XS,blue,67,October,11,Monday,2,10
4996,1000,Mandel Fairbanks,Male,71,Lake Audreyborough,Tasmania,894,2021-10-11,2021-10-13,4480,1177,99.0,2,198.0,Trousers,High-Waisted,M,blue,52,October,11,Monday,2,10
4997,1000,Mandel Fairbanks,Male,71,Lake Audreyborough,Tasmania,894,2021-10-11,2021-10-13,4482,109,92.0,3,276.0,Shirt,Denim,XL,red,63,October,11,Monday,2,10
4998,1000,Mandel Fairbanks,Male,71,Lake Audreyborough,Tasmania,894,2021-10-11,2021-10-13,4481,1239,112.0,1,112.0,Trousers,Tracksuit Bottoms,XL,yellow,59,October,11,Monday,2,10
4999,1000,Mandel Fairbanks,Male,71,Lake Audreyborough,Tasmania,894,2021-10-11,2021-10-13,4477,160,91.0,3,273.0,Shirt,Linen,XS,blue,53,October,11,Monday,2,10

In [36]:
# Sales trend per month with values on each point
sorted_df = df.sort_values(by = 'month', ascending = True)
plot_df = sorted_df.groupby('month')['total_price'].sum().reset_index()
px.line(plot_df, x = 'month', y = 'total_price',
        title = 'Sales Trend Over Time', labels={'total_price': 'Total Sales ($)', 'month': 'Order Month'}, text = 'total_price').update_traces(textposition='top center').show()

In [37]:
df.head()

,customer_id,customer_name,gender,age,city,state,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,stock,order_month_name,order_day,order_weekday_name,delivery_days,month
0,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,670,2021-03-06,2021-04-01,3326,179,98.0,1,98.0,Shirt,Camp Collared,XL,red,79,March,6,Saturday,26,3
1,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,729,2021-02-18,2021-03-01,3640,558,98.0,1,98.0,Jacket,Leather,L,violet,78,February,18,Thursday,11,2
2,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,729,2021-02-18,2021-03-01,3639,197,98.0,3,294.0,Shirt,Camp Collared,M,blue,65,February,18,Thursday,11,2
3,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,670,2021-03-06,2021-04-01,3327,789,91.0,3,273.0,Jacket,Pullover,XL,green,65,March,6,Saturday,26,3
4,1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,455,2021-04-04,2021-04-06,2246,783,91.0,2,182.0,Jacket,Pullover,L,yellow,43,April,4,Sunday,2,4

# Save Cleaned Dataframe

In [38]:
df.to_csv('cleaned_data.csv', index = False)

In [39]:
pd.read_csv('cleaned_data.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         5000 non-null   int64
 1   customer_name       5000 non-null   str
 2   gender              5000 non-null   str
 3   age                 5000 non-null   int64
 4   city                5000 non-null   str
 5   state               5000 non-null   str
 6   order_id            5000 non-null   int64
 7   order_date          5000 non-null   str
 8   delivery_date       5000 non-null   str
 9   sales_id            5000 non-null   int64
 10  product_id          5000 non-null   int64
 11  price_per_unit      5000 non-null   float64
 12  quantity            5000 non-null   int64
 13  total_price         5000 non-null   float64
 14  product_type        5000 non-null   str
 15  product_name        5000 non-null   str
 16  size                5000 non-null   str
 17  colour              5000 non-null   str
 18  stock               5000 non-null   int64
 19  order_month_name    5000 non-null   str
 20  order_day           5000 non-null   int64
 21  order_weekday_name  5000 non-null   str
 22  delivery_days       5000 non-null   int64
 23  month               5000 non-null   int64
dtypes: float64(2), int64(10), str(12)
memory usage: 1.4 MB

In [40]:
df.to_parquet('cleaned_data.parquet', index = False)

In [41]:
pd.read_parquet('cleaned_data.parquet').info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         5000 non-null   int64
 1   customer_name       5000 non-null   str
 2   gender              5000 non-null   str
 3   age                 5000 non-null   int64
 4   city                5000 non-null   str
 5   state               5000 non-null   str
 6   order_id            5000 non-null   int64
 7   order_date          5000 non-null   datetime64[ms]
 8   delivery_date       5000 non-null   datetime64[ms]
 9   sales_id            5000 non-null   int64
 10  product_id          5000 non-null   int64
 11  price_per_unit      5000 non-null   float64
 12  quantity            5000 non-null   int64
 13  total_price         5000 non-null   float64
 14  product_type        5000 non-null   str
 15  product_name        5000 non-null   str
 16  size                5000 non-null   str
 17  colour              5000 non-null   str
 18  stock               5000 non-null   int64
 19  order_month_name    5000 non-null   str
 20  order_day           5000 non-null   int32
 21  order_weekday_name  5000 non-null   str
 22  delivery_days       5000 non-null   int64
 23  month               5000 non-null   int32
dtypes: datetime64[ms](2), float64(2), int32(2), int64(8), str(10)
memory usage: 1.3 MB

In [48]:
df.select_dtypes(include = 'number').columns.drop(['customer_id', 'order_id', 'product_id', 'sales_id'])

Index(['age', 'price_per_unit', 'quantity', 'total_price', 'stock',
       'order_day', 'delivery_days', 'month'],
      dtype='str')

In [47]:
df.select_dtypes(include = 'object').columns.drop('customer_name')

C:\Users\hp\AppData\Local\Temp\ipykernel_31408\751790733.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include = 'object').columns.drop('customer_name')

Index(['gender', 'city', 'state', 'product_type', 'product_name', 'size',
       'colour', 'order_month_name', 'order_weekday_name'],
      dtype='str')